<?php

/**
 * Implements hook_menu().
 */
function webpivot_menu() {
  $item['admin/config/webpivot'] = array(
    'title' => 'Web Pivot',
    'description' => 'Select Multiple Views for Data analysis',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $item['admin/config/webpivot/settings'] = array(
    'title' => 'Web Pivot Settings',
    'description' => 'Select Views for Using Pivot Table Functionlity',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('web_pivot_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'webpivot.admin.inc',
  );
  $item['pivot'] = array(
    'page callback' => 'my_page_function',
    'page arguments' => array('pivot_table'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $item;
}

/**
 * Menu call back function 
 */
function my_page_function(){
  // Call theme() function, so that Drupal includes the custom-page.tpl.php template
  return theme('my_custom_template');
}
   
/*
 * Implementation of hook_theme().
 */
function webpivot_theme(){
  $path = drupal_get_path('module','webpivot');
  return array(
    'my_custom_template' => array(
      // template file name will be custom-page.tpl.php
      'template' => 'pivot-page',
      'path' => "$path",
    ),
  );
}

/*
 * Implementation of hook_page_build().
 */
function webpivot_page_build(&$page) {
  $url = current_path();
  $views_name_unserialize = variable_get('webpivot_serialzed');
  foreach ($views_name_unserialize as $key => $value) {
    $check = variable_get('webpivot_' . $value['machine_name']);
    $conver_url = str_replace("_", "-", $value['machine_name']);
    if ($url == $conver_url) {
      if ($check == 1) {
		 drupal_add_js(drupal_get_path('module', 'webpivot') . '/webpivot.js');
		 $image_path = drupal_get_path('module','webpivot')."/images/button.png";
		 $page['content']['disclaimer'] = array(
	      '#markup' => '<a href="#" onclick="get_value_from_table()"><img src='.$image_path.' /></a>',
	      '#weight' => 25,
	    );
	  }
	}
  }
}


